export const SEARCH_FIELD_FOCUS = 'header/SEARCH_FIELD_FOCUS';
export const SEARCH_FIELD_BLUR = 'header/SEARCH_FIELD_BLUR';
export const GET_SEARCH_RECOMMAND_DATA = 'header/GET_SEARCH_RECOMMAND_DATA';